[package]
name = "rvet"
description = "CLI tool for processing traces in the RISC-V E-Trace format"
authors = ["Julian Ganz <ganz@fzi.de>"]
license = "Apache-2.0"
version = "0.2.0"
edition = "2024"
keywords = ["riscv", "tracing"]
categories = ["command-line-utilities"]
repository = "https://github.com/fzi-forschungszentrum-informatik/rvet"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
cli-table = { version = "0.5", default-features = false, features = ["title"] }
either = "1.15"
elf = "0.8"
pager = { version = "0.16", optional = true }
riscv-etrace = { version = "0.9", features = ["alloc", "either", "elf", "riscv-isa", "serde"] }
riscv-isa = "0.3"
toml = { version = "0.9", features = ["parse"] }
